name: linter-actions
on: [push]
path:
  - 'scripts/*.sh'
jobs:
  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: "scripts/*.sh"
